# add_executable(my_point_cloud_load_and_vis my_point_cloud_load_and_vis.cc)
# target_link_libraries(my_point_cloud_load_and_vis
#         ${PCL_LIBRARIES}
#         ${GLOG_LIBRARIES}
#         gflags
#         )

# # add_executable(my_pcd_to_bird_eye my_pcd_to_bird_eye.cc)
# # target_link_libraries(my_pcd_to_bird_eye
# #         ${PCL_LIBRARIES}
# #         ${GLOG_LIBRARIES}
# #         ${OpenCV_LIBS}
# #         gflags
# #         )

# # add_executable(my_scan_to_range_image my_scan_to_range_image.cc)
# # target_link_libraries(my_scan_to_range_image
# #         ${PCL_LIBRARIES}
# #         ${GLOG_LIBRARIES}
# #         ${OpenCV_LIBS}
# #         gflags
# #         )

# # add_library(${PROJECT_NAME}.ch5_my
# #         my_bfnn.cc
# #         # kdtree.cc
# #         # octo_tree.cc
# #         )

# # target_link_libraries(${PROJECT_NAME}.ch5_my
# #         tbb
# #         )

# # # add_executable(linear_fitting linear_fitting.cc)
# # # target_link_libraries(linear_fitting
# # #         ${PCL_LIBRARIES}
# # #         ${GLOG_LIBRARIES}
# # #         ${OpenCV_LIBS}
# # #         gflags
# # #         )

# # ADD_EXECUTABLE(my_test_nn my_test_nn.cc)
# # ADD_TEST(my_test_nn my_test_bfnn)

# # target_link_libraries(my_test_nn
# #         gtest gmock pthread glog gflags ${PROJECT_NAME}.ch5_my ${PROJECT_NAME}.common ${PCL_LIBRARIES} tbb
# #         )
